# Configuration for the Zizmor static analysis tool (https://woodruffw.github.io/zizmor/configuration/)
# Typically run via pre-commit in CI pipelines

rules:
  dangerous-triggers:
    ignore:
      - documentation-links.yml  # Ignorar avisos em arquivo específico

  unpinned-uses:
    config:
      policies:
        "*": ref-pin  # Aplicar política 'ref-pin' para todas as dependências
