contact_links:
  - name: "📚 Getting Help"
    url: "https://discuss.python.org/c/users/7"
    about: >
      Pergunte dúvidas sobre o uso do Python, erros comuns e resolução de bugs.
      Use o fórum Discourse da comunidade para isso.

  - name: "💡 Proposing New Features"
    url: "https://discuss.python.org/c/ideas/6"
    about: >
      Para grandes sugestões (como mudanças na linguagem ou recursos), primeiro publique sua ideia no fórum de ideias do Discourse.
